name 'common_attrs'
maintainer 'Jonathan Serafini'
maintainer_email 'jonathan@serafini.ca'
license 'apachev2'
description 'Installs/Configures common_attrs'
long_description 'Installs/Configures common_attrs'
version '0.1.0'
