name 'common_attrs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures common_attrs'
long_description 'Installs/Configures common_attrs'
version '0.1.0'
